"""add_system_config

Revision ID: 16867d038b9a
Revises:
Create Date: 2026-03-13 00:11:05.862876
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "16867d038b9a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
