"""Add Resume table

Revision ID: 3bb3134a53ef
Revises: 16867d038b9a
Create Date: 2026-03-21 13:27:58.516079
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3bb3134a53ef'
down_revision: Union[str, None] = '16867d038b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=False),
    sa.Column('parsed_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('target_job_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['target_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_is_original'), 'resumes', ['is_original'], unique=False)
    op.create_index(op.f('ix_resumes_target_job_id'), 'resumes', ['target_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_target_job_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_is_original'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
